baseURL = 'https://zurikheyzho.com/'
languageCode = 'ja-JP'
title = 'Zurikheyzho'
theme = 'my-theme'

[markup.goldmark.renderer]
    unsafe = true
    
[markup.goldmark.parser]
    autoHeadingID = false
