baseURL = 'https://zurikheyzho.com/'
languageCode = 'ja-JP'
title = 'Zurikheyzho - ヘイソウ語公式'
theme = 'my-theme'
enableRobotsTXT = true
enableGitInfo = true

[markup.goldmark.renderer]
    unsafe = true
    
[markup.goldmark.parser]
    autoHeadingID = false