baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[menus]
    [[menus.main]]
        name = '文法'
        pageRef = '/grammar'
        weight = 10

    [[menus.main]]
        name = '音韻'
        pageRef = '/phonology'
        weight = 20

    [[menus.main]]
        name = '文字'
        pageRef = '/writing-system'
        weight = 30

    [[menus.main]]
        name = '例文集'
        pageRef = '/examples'
        weight = 40

[module]
    [module.hugoVersion]
        extended = false
        min = '0.146.0'
